### PR TITLE
Create Dockerfile and start adapting for MySQL

### PR DESCRIPTION
**Pull request by blm768**
Here's a basic Dockerfile that should get you started. In order to build the image and set up the database (assuming you have a MySQL instance running for testing), you can run `./run.sh init-db.sh`. I'm still getting some MySQL-related errors when I attempt to register, so we'll have to make some additional fixes, but this should be a decent starting point for you.

Note that building the image may take a while; it pulls in a lot of dependencies.

### CODE REVIEW

**Comment by CamdenClark** [comment]
This is awesome. Reviewing asap

**Comment by CamdenClark** [comment]
My first thought on mysql errors would be that there are some syntactic changes between sqlite and mysql.

**Comment by blm768** [comment]
Right after you said that, I realized that the MySQL library uses a different syntax for query parameters. I've updated the queries and made a couple of other minor tweaks. Now most of the code seems to be working properly.

**Comment by CamdenClark** [comment]
I'm running mysqld, ran the following:
```GRANT ALL PRIVILEGES ON *.* TO 'dsuser'@'localhost' IDENTIFIED BY 'dspassword';```
in the mysql terminal
but I'm still getting 
```Traceback (most recent call last):
  File "/usr/local/lib/dscomp/venv/lib/python3.6/site-packages/mysql/connector/network.py", line 514, in open_connection
    self.sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused```

any thoughts? I'll keep hacking on it to get it to work but if you have a quick solution that would be appreciated.

**Comment by CamdenClark** [comment]
I figured that out, apparently I have to connect to a mac specific domain name because docker for mac can't do bridging...

**Comment by CamdenClark** [comment]
Going to merge this. There are still a lot of errors in the database logic currently--I'll make a PR to fix these. I'm just going to hope that the deployment will work with the docker file stuff you've chosen. I trust you!

**Pull request merged**
